


import javax.swing.JOptionPane;
import java.sql.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * 
 */

/**
 *
 * @author MIchael Pauk Sa
 */
public class TransactionForm extends javax.swing.JFrame implements Runnable{
    Thread t;
    /**
     *
     */
    public static int tranID;
    /**
     * Creates new form TransactionForm
     * @param userID
     * @param accID  
     */
    public TransactionForm(String userID,String accID) {
        initComponents();
        txtAccid.setText(accID); 
        txtUser.setText(userID);
        txtTrandate.setText(MiscTools.currDate); 
        t=new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTrandate = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtDamount = new javax.swing.JTextField();
        btnD = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtWamount = new javax.swing.JTextField();
        btnW = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTamount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTto = new javax.swing.JTextField();
        btnT = new javax.swing.JButton();
        rbtnD = new javax.swing.JRadioButton();
        rbtnW = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rbtnT = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtAccid = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        jLabel1.setText("Blah");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        jLabel2.setText("Banking System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Transaction Form"));

        jLabel3.setText("User ID");

        txtUser.setEnabled(false);

        jLabel5.setText("Transaction Date");

        txtTrandate.setEnabled(false);

        txtAmount.setEnabled(false);

        jLabel6.setText("Amount");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Deposit"));

        jLabel7.setText("Amount");

        txtDamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDamountKeyReleased(evt);
            }
        });

        btnD.setText("Deposit");
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnD))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addComponent(txtDamount, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Withdraw"));

        jLabel8.setText("Amount");

        txtWamount.setEnabled(false);
        txtWamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWamountKeyReleased(evt);
            }
        });

        btnW.setText("Withdraw");
        btnW.setEnabled(false);
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnW)
                    .addComponent(txtWamount, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtWamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnW)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Transfer"));

        jLabel9.setText("Amount");

        txtTamount.setEnabled(false);
        txtTamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTamountKeyReleased(evt);
            }
        });

        jLabel10.setText("To(User ID)");

        txtTto.setEnabled(false);

        btnT.setText("Transfer");
        btnT.setEnabled(false);
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtTamount, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtTto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(btnT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtTto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnT)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        buttonGroup1.add(rbtnD);
        rbtnD.setSelected(true);
        rbtnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnW);
        rbtnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnWActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Deposit");

        jLabel12.setText("Withdraw");

        jLabel13.setText("Transfer");

        buttonGroup1.add(rbtnT);
        rbtnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTActionPerformed(evt);
            }
        });

        jLabel4.setText("Account ID");

        txtAccid.setEnabled(false);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtnD)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(150, 150, 150)))
                                .addGap(36, 36, 36))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txtAccid))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnW)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTrandate)
                                .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                        .addGap(57, 57, 57))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(rbtnT)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTrandate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(txtAccid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnW, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtnD, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnT)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDActionPerformed
        txtDamount.setEnabled(true);
        txtWamount.setEnabled(false);
        btnW.setEnabled(false);
        btnD.setEnabled(true);
        btnT.setEnabled(false);
        txtTamount.setEnabled(false);
        txtTto.setEnabled(false);
        txtWamount.setText(""); 
        txtTamount.setText("");
        txtTto.setText(""); 
    }//GEN-LAST:event_rbtnDActionPerformed

    private void rbtnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnWActionPerformed
        txtDamount.setEnabled(false);
        btnD.setEnabled(false);
        txtWamount.setEnabled(true);
        btnW.setEnabled(true);
        txtTamount.setEnabled(false);
        txtTto.setEnabled(false);
        btnT.setEnabled(false);
        txtDamount.setText(""); 
        txtTto.setText(""); 
        txtTamount.setText(""); 
    }//GEN-LAST:event_rbtnWActionPerformed

    private void rbtnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTActionPerformed
        txtDamount.setEnabled(false);
        btnD.setEnabled(false);
        txtWamount.setEnabled(false);
        btnW.setEnabled(false);
        txtTamount.setEnabled(true);
        txtTto.setEnabled(true);
        btnT.setEnabled(true); 
        txtDamount.setText(""); 
        txtWamount.setText(""); 
    }//GEN-LAST:event_rbtnTActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        if(txtDamount.getText().isEmpty())  {
            JOptionPane.showMessageDialog(null,"Enter Amount to deposit!");
            return;
        }
        try {
            MiscTools.sta.executeUpdate("UPDATE ACCOUNT SET AMOUNT="+(Double.parseDouble(txtAmount.getText())+Double.parseDouble(txtDamount.getText()))+" WHERE USERID='"+txtUser.getText()+"';");
            JOptionPane.showMessageDialog(null,"Successfully Done!");
            MiscTools.sta.executeUpdate("INSERT INTO TRANSACTION(TRANSACTIONID,USERID,TYPE,DESTINATION,DOT,AMOUNT,ACCID) VALUES ("+tranID+",'"+txtUser.getText()+"','Deposits','-','"+txtTrandate.getText()+"',"+txtDamount.getText()+","+txtAccid.getText()+");"); 
            messClean();
            txtAmount.setText(String.valueOf(Double.parseDouble(txtAmount.getText())+Double.parseDouble(txtDamount.getText()))); 
            txtDamount.setText("");       
        }catch(SQLException e)  {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnDActionPerformed

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
        if(txtWamount.getText().isEmpty())  {
            JOptionPane.showMessageDialog(null,"Enter Amount to withdraw!");
            return;
        }
        try {
            ResultSet rs=MiscTools.sta.executeQuery("SELECT AMOUNT FROM ACCOUNT WHERE USERID='"+txtUser.getText()+"';");
            rs.next();
            if((Double.parseDouble(txtAmount.getText())-Double.parseDouble(txtWamount.getText()))<3000)  {
                JOptionPane.showMessageDialog(null,"Your Amount is not enought for the Transaction!At least 3000 must be in the account.");
                return;
            }
            MiscTools.sta.executeUpdate("UPDATE ACCOUNT SET AMOUNT ="+(Double.parseDouble(txtAmount.getText())-Double.parseDouble(txtWamount.getText()))+" WHERE USERID='"+txtUser.getText()+"';");
            MiscTools.sta.executeUpdate("INSERT INTO TRANSACTION(TRANSACTIONID,USERID,TYPE,DESTINATION,DOT,AMOUNT,ACCID) VALUES ("+tranID+",'"+txtUser.getText()+"','Deposits','-','"+txtTrandate.getText()+"',"+txtWamount.getText()+","+txtAccid.getText()+");");
            messClean();
            JOptionPane.showMessageDialog(null,"Successfully Done!");
            txtAmount.setText(String.valueOf(Double.parseDouble(txtAmount.getText())-Double.parseDouble(txtWamount.getText()))); 
            txtWamount.setText("");
        }catch(SQLException e)  {
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_btnWActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        if(txtTamount.getText().isEmpty()||txtTto.getText().isEmpty())  {
            JOptionPane.showMessageDialog(null,"Enter These Two Required Forms!");
            return;
        } 
        if(txtTto.getText().equals(txtUser.getText()))  {
            JOptionPane.showMessageDialog(null,"You can't Transfer to yourself!");
            txtTto.setText(""); 
            return;
        }
        try {
            ResultSet rs=MiscTools.sta.executeQuery("SELECT ACCID FROM ACCOUNT WHERE USERID='"+txtTto.getText()+"';");
            if(!rs.next())  {
                JOptionPane.showMessageDialog(null,"Destination UserID doesn't Exist!");
                txtTto.setText("");
                return;
            }
            rs=MiscTools.sta.executeQuery("SELECT BLOCKID FROM BLOCK WHERE ACCID=(SELECT ACCID FROM ACCOUNT WHERE USERID='"+txtTto.getText()+"');");
            if(rs.next())  {
                JOptionPane.showMessageDialog(null,"It's a blocked account!");
                return;
            }
            rs=MiscTools.sta.executeQuery("SELECT AMOUNT FROM ACCOUNT WHERE USERID='"+txtUser.getText()+"';");
            rs.next();
            if((Double.parseDouble(txtAmount.getText())-Double.parseDouble(txtTamount.getText()))<3000)  {
                JOptionPane.showMessageDialog(null,"Your Amount is not enought for the Transaction!At least 3000 must be in the account.");
                return;
            }
            MiscTools.sta.executeUpdate("UPDATE ACCOUNT SET AMOUNT="+(Double.parseDouble(txtAmount.getText())-Double.parseDouble(txtTamount.getText()))+" WHERE USERID='"+txtUser.getText()+"';"); 
            MiscTools.sta.executeUpdate("UPDATE ACCOUNT SET AMOUNT="+(Double.parseDouble(txtAmount.getText())+Double.parseDouble(txtTamount.getText()))+" WHERE USERID='"+txtTto.getText()+"';");
            JOptionPane.showMessageDialog(null,"Successfully Done!"); 
            MiscTools.sta.executeUpdate("INSERT INTO TRANSACTION(TRANSACTIONID,USERID,TYPE,DESTINATION,DOT,AMOUNT,ACCID) VALUES ("+tranID+",'"+txtUser.getText()+"','Transfer','"+txtTto.getText()+"','"+txtTrandate.getText()+"',"+txtTamount.getText()+","+txtAccid.getText()+");");
            txtTto.setText("");
            txtTamount.setText("");
            messClean();
        }catch(SQLException e)  {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnTActionPerformed

    private void txtDamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDamountKeyReleased
        try {
            Double.parseDouble(txtDamount.getText());
        }catch(NumberFormatException e) {
            txtDamount.setText("");
        }
    }//GEN-LAST:event_txtDamountKeyReleased

    private void txtWamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWamountKeyReleased
        try {
            Double.parseDouble(txtWamount.getText());
        }catch(NumberFormatException e)  {
            txtWamount.setText(""); 
        }
    }//GEN-LAST:event_txtWamountKeyReleased

    private void txtTamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamountKeyReleased
        try {
            Double.parseDouble(txtTamount.getText()); 
        } catch(NumberFormatException e)  {
            txtTamount.setText("");
        }
    }//GEN-LAST:event_txtTamountKeyReleased

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
        t.interrupt();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     *
     */
    public static synchronized void getTran()  {
        try {
            ResultSet rs=MiscTools.sta.executeQuery("SELECT * FROM TRANRECYCLE ORDER BY TRANID;");
            if(rs.next())  {
                tranID=rs.getInt("TranID");
                return;
            }
            rs=MiscTools.sta.executeQuery("SELECT COUNT(TRANSACTIONID) FROM TRANSACTION;");
            rs.next();
            tranID=(rs.getInt(1)+1);
        }catch(SQLException e)  {
                JOptionPane.showMessageDialog(null, e);
                tranID=-1;
        }
    }
    @Override
    public void run()  {
        try {
            while(!Thread.currentThread().isInterrupted())  {
                txtAmount.setText(String.valueOf(MiscTools.checkAmt(txtUser.getText()))); 
                if(Double.parseDouble(txtAmount.getText())==0)  
                    Thread.currentThread().interrupt();
                Thread.sleep(5000);
            }
        }catch(InterruptedException e) {
            if(this.isDisplayable())  {
                JOptionPane.showMessageDialog(null,"Something's wrong with the account!");
                this.dispose();
            }
        }
    }
    /**
     *
     */
    public static synchronized void messClean()  {
        try {
            Statement s=MiscTools.c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs=s.executeQuery("SELECT TRANID FROM TRANRECYCLE WHERE TRANID="+tranID+";");
            if(rs.next())
            s.executeUpdate("DELETE * FROM TRANRECYCLE WHERE TRANID="+tranID+";");
            s.close();
        }catch(SQLException e)  {}
        getTran();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args)  {
        MiscTools.isConnectable();
        TransactionForm tf=new TransactionForm("0304051","1");
        tf.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnW;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rbtnD;
    private javax.swing.JRadioButton rbtnT;
    private javax.swing.JRadioButton rbtnW;
    private javax.swing.JTextField txtAccid;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDamount;
    private javax.swing.JTextField txtTamount;
    private javax.swing.JTextField txtTrandate;
    private javax.swing.JTextField txtTto;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtWamount;
    // End of variables declaration//GEN-END:variables
}
